site_name: Homelab Documentation
site_description: 'This is my homelab documentation that includes pretty much everything to do with my current lab.'
site_author: 'thesyntaxslinger'
site_url: 'https://syntaxslinger.com/' # this gets dynamically changed with a deploy script
copyright: 'Copyright Â© 2025 syntaxslinger.'

repo_name: 'syntaxslinger.com'
repo_url: 'https://github.com/thesyntaxslinger/syntaxslinger.com'


theme:
  name: material
  logo: assets/img/profile-picture.webp
  favicon: assets/img/favicons/favicon.ico
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - privacy
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/thesyntaxslinger

nav:
  - 'Introduction': index.md
  - 'Hypervisor':
    - hypervisor/index.md
    - 'Storage Setup': hypervisor/storage-setup.md
    - 'Backups': hypervisor/backups.md
    - 'Networking': hypervisor/networking.md
  - 'Administration':
    - administration/index.md
    - 'Bootstrapping': administration/bootstrapping.md
    - 'Updates and Patch Management': administration/updates-and-patch-management.md
  - 'Networking':
    - networking/index.md
    - 'DNS': networking/dns.md
    - 'VPNs': networking/vpns.md
    - "VLANs": networking/vlans.md
    - "Firewall": networking/firewall.md
    - 'IPv6': networking/ipv6.md
  - 'Software':
    - software/index.md
    - 'Authelia': software/authelia.md
    - 'Caddy': software/caddy.md
    - 'Gitea': software/gitea.md
    - 'Miniflux': software/miniflux.md
    - 'Nextcloud': software/nextcloud.md
    - 'ntfy': software/ntfy.md
    - 'OwnTracks': software/owntracks.md
    - 'Paperless-ngx': software/paperless-ngx.md
    - 'PostgreSQL': software/postgresql.md
